### ISSUE TITLE
elasticsearch-spark_2.10-2.1.0.Beta2 exception when join with parqustFile

### ISSUE THREAD

**Issue by huangchen007** [elasticsearch/elasticsearch-hadoop#323]
I got exception like below when i worked on spark sql join 

Seems to serialiation problem.

Class cannot be created (missing no-arg constructor): ScalaEsRow

**Comment by costin** [comment]
@huangchen007 Hi, did you manage to test master ?

**Comment by costin** [comment]
As there hasn't been any update and I couldn't reproduce the issue, I'm closing it down. If it keeps on occurring, please open up a new issue.
