### ISSUE TITLE
elasticsearch-hive0.14 issue

### ISSUE THREAD

**Issue by MaheshSankaran** [elasticsearch/elasticsearch-hadoop#333]
Hi
    I am currently working in hive0.14-elasticsearch connection.I use "curl  XPUT" to sent data to elasticsearch . i created elasticsearch based hive table pointing to "es.resource",i could see data but  i cant insert into elasticsearch storage table but it  is working well in hive 0.13.1 and i could see data in it.

hive> insert overwrite table list select * from list_main;
Query ID = hadoop2_20141127124040_dece5520-15a8-4d6d-ab4b-5a95f274f51c
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks is set to 0 since there's no reduce operator
Starting Job = job_1417061780604_0011, Tracking URL = http://nn01:8088/proxy/application_1417061780604_0011/
Kill Command = /opt/hadoop-2.4.1/bin/hadoop job  -kill job_1417061780604_0011
Hadoop job information for Stage-0: number of mappers: 0; number of reducers: 0
2014-11-27 12:40:49,470 Stage-0 map = 0%,  reduce = 0%
Ended Job = job_1417061780604_0011 with errors
Error during job, obtaining debugging information...
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Stage-Stage-0:  HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec

**Comment by justinjoseph89** [comment]
@costin  I was facing the same issue and once i changed the es-hadoop jar to 2.1.0.BUILD-SNAPSHOT its working perfectly.
Thanks,
Justin Joseph

**Comment by costin** [comment]
@justinjoseph89 Thanks for the info!. Closing the issue.
