### ISSUE TITLE
How to insert data hive in elasticsearch if i finish create table with STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'..? 

### ISSUE THREAD

**Issue by Jayusman123** [elasticsearch/elasticsearch-hadoop#361]
How to insert data hive in elasticsearch if i finish create table with STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'..? 

Because i found error... dont insert file.csv..

example query create table:

create table test 
(id string, name string, gender string, hits bigint)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES
(
'es.resource' = 'jay/member'
);

iam using this.. but error..:
load data inpath
'/user/hue/es.csv' 
into table `default.test`;

**Comment by costin** [comment]
There's a [mailing](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/index.html) for asking question and documentation explaining how to use es-hadoop. The issue tracker is not the appropriate place to ask questions.

Thank you
