### ISSUE TITLE
create Scala 2.11 artifact in addition to Scala 2.10

### ISSUE THREAD

**Issue by costin** [elasticsearch/elasticsearch-hadoop#376]
While Spark doesn't provide a 2.11 artifact (yet though it looks like 1.2.1 will address that), it is source compatible with it. As such, es-spark should provide a dedicated artifact for it as well.

**Comment by deepakas** [comment]
Hi Costin, Thanks for making the build. I dont see   v2.1.0.Beta4 in github or in the maven repository.  Am I looking the wrong place ?

https://github.com/elasticsearch/elasticsearch-hadoop/tree/v2.1.0.Beta4
http://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-hadoop

**Comment by costin** [comment]
Yes you are. It's a dev/snapshot build and thus it is deployed in a different repo - see [this](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/install.html#download-dev) section for more details. Once 2.1.0.Beta4 is released, you should be able to see it in those repos as well.

**Comment by deepakas** [comment]
Thanks. I got it and was able to build with out any exclusion. Also I tested locally on two of my spark jobs. . I was wondering why the scala.xml was working with Beta1 version if the issue was related to build on Scala 2.10.

**Comment by costin** [comment]
@deepakas Great! Thanks for the quick feedback! Closing the issue as fixed.
