### ISSUE TITLE
[Spark] Case Class example failed after compile

### ISSUE THREAD

**Issue by simonlei** [elasticsearch/elasticsearch-hadoop#378]
I'm using elasticsearch-hadoop's spark(es-hadoop version 2.1.0.BUILD-20150213.023404-297.jar/scala version 2.10.4/spark version 1.2.1) to write some case class to es, and tried the example code on 
http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/spark.html
```
import org.apache.spark.SparkContext
import org.elasticsearch.spark.rdd.EsSpark                        

// define a case class
case class Trip(departure: String, arrival: String)               

val upcomingTrip = Trip("OTP", "SFO")
val lastWeekTrip = Trip("MUC", "OTP")

val rdd = sc.makeRDD(Seq(upcomingTrip, lastWeekTrip))           
EsSpark.saveToEs(rdd, "spark/docs")                               
```
When I use 
bin/spark-shell --jars ~/Downloads/elasticsearch-hadoop-2.1.0.BUILD-20150213.023404-297.jar
to run the code, it works fine. But if I write the code in a scala file, then compile it and run, it will failed.
The elasticsearch report :
```
Caused by: org.elasticsearch.ElasticsearchParseException: Failed to derive xcontent from (offset=40, length=13): [123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10, 91, 34, 79, 84, 80, 34, 44, 34, 83, 70, 79, 34, 93, 10, 123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10, 91, 34, 77, 85, 67, 34, 44, 34, 79, 84, 80, 34, 93, 10]
```
Which means it post 
```
{"index":{}}
["OTP","SFO"]
{"index":{}}
["MUC","OTP"]
```
instead of correct json to elasticsearch.

I checked the source code, found it caused by the "isCaseClass" method at 
[ReflectionUtils.scala](https://github.com/elasticsearch/elasticsearch-hadoop/blob/master/spark/src/main/scala/org/elasticsearch/spark/serialization/ReflectionUtils.scala)
caused by the issue of scala

[isCaseClass returns true for case object's module class](https://issues.scala-lang.org/browse/SI-8295)
and someone find the same issue on scala:
http://stackoverflow.com/questions/12377046/scala-2-10-reflection-classsymbol-iscaseclass-works-in-scala-console-but-not-in

Maybe ReflectionUtils should use another way to implement isCaseClass.
The code from [the answer](http://stackoverflow.com/questions/7525142/how-to-programmatically-determine-if-the-the-class-is-a-case-class-or-a-simple-c) works both for the shell and the compiled version:
```
def isCaseClass(o: AnyRef) = o.getClass.getInterfaces.find(_ == classOf[scala.Product]) != None
```
Thanks.

**Comment by costin** [comment]
@simonlei Frustrating to see `isCaseClass` doesn't work universally. Without it, one ends up with an approximation which isn't ideal; for example in your case any class that's a `Product` is considered a case class even though that's not the case.
This is important when reading the case class properties as they need to be properly resolved.

Just to make sure I understand the issue, if you use a stand-alone case class, the case class reflection, fails correct?

**Comment by simonlei** [comment]
@costin Thanks for your reply. 
I'm just touching the spark and scale for few days, mine solution for isCaseClass was searched from web, I didn't know it's a good one or not. Sorry.

To reproduce the bug is easy, I post the source in [gist](https://gist.github.com/simonlei/7b88cf5c5cd9853cb935)
I'm using [sbt-pack](https://github.com/xerial/sbt-pack) to build the standalone application. 
The directory struct just like:

![image 15-2-16 at 23 01](https://cloud.githubusercontent.com/assets/2107131/6214015/6cffc812-b630-11e4-9dce-41f9669bedc3.jpg)

Just run ```sbt pack``` to build the standalone application, and run ```target/pack/bin/test-is-case-class```
You will see the [errors](https://gist.github.com/simonlei/6dd9542c9173012d79de)

The same code works fine at spark-shell with the same jar files
```bin/spark-shell --jars ~/Downloads/elasticsearch-hadoop-2.1.0.BUILD-20150213.023404-297.jar```

**Comment by costin** [comment]
@simonlei Hi,
I've pushed a fix in master which should address your issue. I've tested against your project (thanks for that) and it seems to be working. Notice you'll get a warning to indicate that things might not always work.
From what I can tell, under sbt alone, your case class does not have the relevant `@ScalaSignature` which means the Scala reflection doesn't know much about this class and thus it cannot tell whether it's a case class or not.
The fallback is to use some type of detection using Java reflection which should be pretty accurate except the field properties - we can't tell just through Reflection what properties (vs nested `var`s which are allowed but not used in the `Product`) you actually use and their order.
We simply hope the bytecode preserves the field declaration order - and that is not guaranteed by the JVM. Thus, one can end up with the properties switched and unfortunately there's not much we can do in this case. The only solution is to really have the relevant bytecode in there...

Please try it out and let me know how it goes; I've pushed the dev builds already

**Comment by simonlei** [comment]
@costin Great! The version elasticsearch-hadoop-2.1.0.BUILD-20150227.023402-314.jar works, thanks!

**Comment by costin** [comment]
Thanks for confirming. Closing the issue
