### ISSUE TITLE
Saving case class with mapping id error

### ISSUE THREAD

**Issue by simonlei** [elasticsearch/elasticsearch-hadoop#384]
Start the spark-shell with today's snapshot jar:
```bin/spark-shell --jars ~/Download/elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar```

Then, run codes below:
```
    import org.elasticsearch.spark.rdd.EsSpark                        
    case class Trip(id:Integer, departure: String, arrival: String)               

    val upcomingTrip = Trip( 1, "OTP", "SFO")
    val lastWeekTrip = Trip( 2, "MUC", "OTP")

    val rdd = sc.makeRDD(Seq(upcomingTrip, lastWeekTrip))
    EsSpark.saveToEs(rdd, "spark/docs2", Map( "es.mapping.id"->"id"))
```
Then it will throw [exceptions](https://gist.github.com/simonlei/3d4f0e53143d5c069ec2)

This issue is related to [[Spark] Case Class example failed after compile](https://github.com/elasticsearch/elasticsearch-hadoop/issues/378), but without the es.mapping.id, it works fine, so I create a new one.

Thanks.

**Comment by costin** [comment]
@simonlei Pushed in master and the dev builds in master. can you please try them out?

Thanks,

**Comment by simonlei** [comment]
@costin Great! It works with the snapshot version elasticsearch-hadoop-2.1.0.BUILD-20150302.222111-319.jar, both for the spark-shell and compiled jars. 

Thanks!

**Comment by costin** [comment]
Cheers - closing the issue.
